;;;; srfi.x4.import.scm - GENERATED BY CHICKEN 5.0.0 -*- Scheme -*-

(##sys#register-compiled-module
  'srfi.x4
  'srfi.x4
  (scheme#list)
  '((make-u1vector . srfi.x4#make-u1vector)
    (make-c64vector . srfi.x4#make-c64vector)
    (make-c128vector . srfi.x4#make-c128vector)
    (u1vector . srfi.x4#u1vector)
    (c64vector . srfi.x4#c64vector)
    (c128vector . srfi.x4#c128vector)
    (u1vector? . srfi.x4#u1vector?)
    (c64vector? . srfi.x4#c64vector?)
    (c128vector? . srfi.x4#c128vector?)
    (u1vector-length . srfi.x4#u1vector-length)
    (c64vector-length . srfi.x4#c64vector-length)
    (c128vector-length . srfi.x4#c128vector-length)
    (u1vector-ref . srfi.x4#u1vector-ref)
    (c64vector-ref . srfi.x4#c64vector-ref)
    (c128vector-ref . srfi.x4#c128vector-ref)
    (u1vector-set! . srfi.x4#u1vector-set!)
    (c64vector-set! . srfi.x4#c64vector-set!)
    (c128vector-set! . srfi.x4#c128vector-set!)
    (u1vector->list . srfi.x4#u1vector->list)
    (c64vector->list . srfi.x4#c64vector->list)
    (c128vector->list . srfi.x4#c128vector->list)
    (list->u1vector . srfi.x4#list->u1vector)
    (list->c64vector . srfi.x4#list->c64vector)
    (list->c128vector . srfi.x4#list->c128vector))
  (scheme#list)
  (scheme#list))

;; END OF FILE
